### ISSUE TITLE
PlotOverlay function

### ISSUE THREAD

**Issue by ameziyi** [veeninglab/BactMAP#12]
Hi Renske, 

For the plotOverlay function, when I use the example dataset (https://github.com/veeninglab/BactMAP/wiki/subcellular-localization#plotoverlay), there would be an error message said: [ Error: incorrect size (1) at position 1, expecting : 429]. I also tried my own data and a similar error message would show up.

Just letting you know and take your time.

Thanks!
Ziyi

**Comment by vrrenske** [comment]
This issue is now solved in the development version of BactMAP (downloadable via `remotes::install_github("vrrenske/bactmap")` 
Let me know if it works now or that I missed something, I will update the solutions to the stable version in the coming weeks!

**Comment by vrrenske** [comment]
this resolve is now updated in the stable function of bactMAP
