### ISSUE TITLE
ggtree installation problems (MacOS)

### ISSUE THREAD

**Issue by veeninglab** [veeninglab/BactMAP#3]
ggtree is currently a required import when installing BactMAP, but this can lead to problems when installing the package on a Mac. We are working on a solution for this.

Until then, to install BactMAP on Mac, install ggtree manually first via Bioconductor:

```r
if (!requireNamespace("BiocManager", quietly = TRUE))
    install.packages("BiocManager")
BiocManager::install("ggtree")
```
After this, proceed to install BactMAP as instructed [here](https://github.com/veeninglab/BactMAP/wiki/Download-&-Install-BactMAP).

For more information on installation of ggtree and its dependencies, see https://bioconductor.org/packages/release/bioc/html/ggtree.html

**Comment by vrrenske** [comment]
Solved by updating dependency page for automated bioconductor installation.
